apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:                # ✅ belongs directly under spec
    app: vproapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP           # or NodePort / LoadBalancer as needed
