apiVersion: v1
kind: Service
metadata:
  name: vprocached01
spec:
  selector:
    app: vprodb
  ports:
  - port: 11211
    targetPort: vpromc
    protocol: TCP
    selector:
      app: vpromc
  type: ClusterIP